### ISSUE TITLE
Errors not showing on Workshop form

### ISSUE THREAD

**Issue by danielfowler** [edalzell/statamic-charge#14]
**Description:**
Workshop form is submitting successfully, even when Stripe rejects the transaction.

**Expected behavior:**
If user submits an invalid billing credential (like zip code), they would see visual error and the form would not submit.

**Actual behavior:**
Stripe logs the zip code error, but the form submits successfully.

**Code sample:**
```
{{ workshop:entry:create collection="shows" slugify="namesake" attr="id:post-new-show|data-charge-form" redirect="{ current_url }?success=true" }}
  {{ charge:errors }}
  {{ partial:forms-errors }}
```

**Comment by edalzell** [comment]
Not sure I can stop the submission...Workshop isn't set to do that.

I can get the errors working though, is that good enough @danielfowler ?

**Comment by danielfowler** [comment]
How would they work if the form still submits?

**Comment by edalzell** [comment]
No clue, that would be a workshop issue not a Charge issue.

I'll have to dig in further to see what's possible.

**Comment by edalzell** [comment]
Ya I can stop the saving, you'll have to check for charge errors yourself then redirect if appropriate.
