### ISSUE TITLE
Payment fields not required when using Workshop form

### ISSUE THREAD

**Issue by danielfowler** [edalzell/statamic-charge#2]
I can submit a Charge-enabled form without filling in the payment details even though the HTML fields are marked as `required`. The error code that Stripe throws is 
```
[2018-08-27 17:52:04] production.ERROR: Cannot charge a customer that
has no active card [] []
```

**Comment by edalzell** [comment]
Can you please share your form template? And what version of Workshop?

What's the error you get?

**Comment by danielfowler** [comment]
Updated my comment with error code. I was wrong - it's not a fatal error, just a log.

**Comment by danielfowler** [comment]
Workshop v1.0

**Comment by edalzell** [comment]
Please post your form template @danielfowler, so I can try to reproduce
