### ISSUE TITLE
E-mails don't get sent

### ISSUE THREAD

**Issue by studio1902** [edalzell/statamic-charge#39]
Charge doesn't sent emails for me after subscribing a customer.

Could it have something to do with the function themeFolder() in SendEmailAction.php not respecting running above the webroot?

**Comment by studio1902** [comment]
Is there a benefit too using the Charge emails rather than the Stripe emails aside from styling and customisation?

**Comment by edalzell** [comment]
Ya I might turn this feature off to make things simpler. Do you prefer to use Stripe's stuff? or keep everything in Statamic @studio1902?

**Comment by studio1902** [comment]
I thought I wanted to keep in Statamic to get fine grained control but as soon as I saw the default mail combined with the branding you can add to it I was sold. The Stripe mails are fine for me. At least on lower budget sites.

**Comment by studio1902** [comment]
I think atm Stripe won't send invoices. You have to enable this on the PHP side:

https://stripe.com/docs/billing/invoices/sending

**Comment by edalzell** [comment]
@studio1902 using Statamic templates right now, if you want Stripe emails, please open a FR.
