### ISSUE TITLE
User doesn't get assigned a role after subscribing

### ISSUE THREAD

**Issue by studio1902** [edalzell/statamic-charge#40]
In my tests users don't get assigned the role I defined in the settings after subscribing to a plan.

**Comment by studio1902** [comment]
All I can see change after subscribing is a customer_id being added to the current user.

**Comment by edalzell** [comment]
Do you have the webhook set up?

**Comment by studio1902** [comment]
Yes. It’s sending stuff too!

**Comment by edalzell** [comment]
how are you exposing your server? ngrok? ultrahook?

**Comment by studio1902** [comment]
Tried Ultrahook, didn't get it to work so I pushed to a staging server.

**Comment by studio1902** [comment]
I do get a customer ID in the user.yaml file and the subscription and customer get pushed to Stripe.

**Comment by studio1902** [comment]
Like a charm
