### ISSUE TITLE
Cancelling a subscription from the stripe dashboard doesn't reflect on site

### ISSUE THREAD

**Issue by studio1902** [edalzell/statamic-charge#48]
When you cancel a subscription from the Stripe dashboard (Billing > Subscriptions) it doesn't seem to invoke the webhook and update the `subscription_status` for the user on your site.

**Comment by edalzell** [comment]
@studio1902 did you cancel immediately or at end of billing period?

**Comment by edalzell** [comment]
note to self: cancelling immediately is the issue. The `customer.subscription.deleted` event needs supporting.

**Comment by edalzell** [comment]
fixed in next beta
