### ISSUE TITLE
test on local machine

### ISSUE THREAD

**Issue by fozzylady** [edalzell/statamic-charge#6]
What is the best way to test on local environment before pushing live on the server?  I am getting the error:

FatalThrowableError in ChargeTags.php line 20:
Class 'Stripe\Stripe' not found.

Guessing it's due to the fact i'm unsure how to  run php please update:addons  as per their instructions at https://statamic.com/marketplace/addons/charge/docs for a non-production environment.
--

**Comment by edalzell** [comment]
from the root of your site, run `php please update:addons` on the command line.

To test locally, expose your dev box via ngrok or similar, then set that exposed url as the Stripe web hook as per the addon instructions.

**Comment by fozzylady** [comment]
I added the web hook and still the same error?

**Comment by edalzell** [comment]
have you exposed your local dev box via ngrok or similar?

**Comment by fozzylady** [comment]
yes still no go.

**Comment by edalzell** [comment]
are you putting the exposed url into the stripe webhook? How are you serving your site? How are you sharing it?

**Comment by edalzell** [comment]
can you pop on the discord channel and we can discuss @fozzylady ?

**Comment by fozzylady** [comment]
please can you send me an invite.

**Comment by edalzell** [comment]
https://discord.gg/hShm7Ru

**Comment by edalzell** [comment]
resolved in discord
