### ISSUE TITLE
charge:update_billing_form tag throws error on submission

### ISSUE THREAD

**Issue by jeremydouglas** [edalzell/statamic-charge#60]
I'm basing my code on the `charge:update_billing_form` tag in the docs. Upon submission, the endpoint `/!/Charge/update_billing` is hit. But, I receive this error on that page:

```
FatalThrowableError in HasParameters.php line 15: Type error: Too few arguments to function Statamic\Addons\Charge\ChargeController::getDetails(), 0 passed in /Users/jeremyhoover/Sites/deboss-garage-api/public/site/addons/Charge/ChargeController.php on line 176 and at least 1 expected

    in HasParameters.php line 15
    at ChargeController->getDetails() in ChargeController.php line 176
    at ChargeController->postUpdateBilling(object(User))
    at call_user_func_array(array(object(ChargeController), 'postUpdateBilling'), array(null)) in Container.php line 507
    at Container->call(array(object(ChargeController), 'postUpdateBilling'), array()) in Container.php line 604
```

**Comment by edalzell** [comment]
@jeremydouglas that's the wrong endpoint, do you have the latest code [release](https://github.com/edalzell/statamic-charge/releases/tag/v3.0.0-beta.5)?

**Comment by jeremydouglas** [comment]
🤦‍♂

**Comment by jeremydouglas** [comment]
K, I'm on `v3.0.0-beta.5` now.

I'm still receiving this error when submitting a `charge:update_billing_form`:

```
FatalThrowableError in HasCustomers.php line 24: Type error: Too few arguments to function Statamic\Addons\Charge\ChargeController::patchCustomer(), 0 passed and exactly 1 expected
```

I've updated [this line](https://github.com/edalzell/statamic-charge/blob/v3.0.0-beta.5/Charge/Traits/HasCustomers.php#L20):

`return $this->createForm('customer/' . $this->getParam('id'), [], 'PATCH');`

to be:

`return $this->createForm('customer/' . $this->getParam('customer_id'), [], 'PATCH');`

This updates the card in Stripe successfully for me.

**Comment by edalzell** [comment]
Let's see that part of the template, should look like this:
```
{{ charge:update_billing_form :id="customer_id" attr="id:foo"}}
```

**Comment by jeremydouglas** [comment]
Yes, I see that you have the param as `id` in the docs now. Sorry, I thought it was `customer_id`.
