### ISSUE TITLE
Documentation improvements (one time)

### ISSUE THREAD

**Issue by studio1902** [edalzell/statamic-charge#61]
A fresh new batch of doc improvements suggestions after the latest updates (01-28-2020).

[One Time Checkout](https://github.com/edalzell/statamic-charge/blob/master/docs/one-time/checkout.md) 
1. `NOTE: the redirectToCheckout does NOT work well with Statamic's form and user form tags as the redirect happens and form submission does not. In general, use Elements (see below) instead.` What is this redirectToCheckout, when should I use it? Apparently I shouldn't. Maybe expand on this a little?
2. `Elements (see below)` I think this part has moved and is no longer relevant.
3. I'd expand on the `Session ID` a little. What is it and why do I need it?
4. When should I use the `tag` method or the `AJAX` method?
5. It seems to me that the AJAX part has the same example. What's different here?

[One Time Elements](https://github.com/edalzell/statamic-charge/blob/master/docs/one-time/elements.md) 
1. Are you using a default statamic form there? `form:create in=""` implies that to me. Do users need to make one before using this method?
2. I'd explain briefly what the `payments intent id` is and why we want one.
3. What's the difference between the `tag` or `AJAX` methods. How do users know which one they want or need. Can you maybe explain the differences in use cases?

In general it's all written from a developer standpoint. I'd try to take the user along a little more and explain what you're going to do so you don't scare off nitwits like me.

**Comment by edalzell** [comment]
Redoing for v3
