### ISSUE TITLE
{{ charge:plans }} limited to 10 results

### ISSUE THREAD

**Issue by theblacksheepltd** [edalzell/statamic-charge#69]
I have a Stripe product with more than  10 subscription plans (used as sponsorship items). Only the first 10 are being returned with the {{ charge:plans }} tag. Is there a setting to increase this?

**Comment by edalzell** [comment]
I'll check, I call the `->all()` method, perhaps Stripe is limiting it?

**Comment by edalzell** [comment]
Yup it's a stripe default
<img width="487" alt="image" src="https://user-images.githubusercontent.com/6069653/74677583-9289a200-516d-11ea-8677-bab96858b1ce.png">

I can add a parameter to override.

**Comment by edalzell** [comment]
released in 3.1
