### ISSUE TITLE
Automatic recurring payment reminder emails with subscription products

### ISSUE THREAD

**Issue by danfascia** [edalzell/statamic-charge#7]
It would be nice if the Stripe feature to allow a payment reminder for impending recurring subscription payments could be implemented into the Charge plugin.

The way I would see this working:

1. Setup the event and a chosen advance time (i.e. 7-days) in Stripe Dashboard
2. The event triggers an email in Charge
3. Charge settings allow this feature to be turned on/off for a plan, and allow a user defined message to be created (like the other event driven emails). It would also be good to incorporate a couple of variables such as: product_name, next_payment_due_date, cancel_link, update_billing_link

**Comment by edalzell** [comment]
Great suggestion @danfascia.

For the can update link, aren't those links you define in your site?

**Comment by danfascia** [comment]
I just meant so that they could be used in the email reminder text

**Comment by edalzell** [comment]
@danfascia but you control the template...can't you just put the links in?

I'm confused.
