### ISSUE TITLE
FR: Supporting taxes

### ISSUE THREAD

**Issue by jeremydouglas** [edalzell/statamic-charge#70]
I need to get taxes (CDN) working with subscriptions. Are there plans to support taxes in the current version?

**Comment by edalzell** [comment]
How would you want it to work?

**Comment by jeremydouglas** [comment]
My requirement is to have taxes applied to subscriptions for Canadians based on their province.

You'll have to excuse me, I'm just learning how Stripe works with taxes. It looks like I could setup tax rates in Stripe and pass in the Tax rate ID when the subscription is created. On a Stripe invoice, it would break out the amount separately. Which is nice.

Users would select their country and province. Then the tax rate would apply based on the province. I'm not collecting a full address at the moment, but maybe I'll need to do that.

Do you have ideas on how I could get this going with the Charge add-on? If it has to be simpler until the next version, that's fine.

**Comment by jeremydouglas** [comment]
For example, I was able to submit a test charge with a tax rate by adding the tax_rates line to the `HasSubscriptions.php` file:

```
$subscription = [
    'customer' => $customer->id,
    'items' => [
        [
            'plan' => $details['plan'],
            'quantity' => Arr::get($details, 'quantity', 1),
            'tax_rates' => [
                'txr_89270235',
            ],
        ],
    ],
    'prorate' => Arr::get($details, 'prorate', true),
    'coupon' => Arr::get($details, 'coupon'),
    'expand' => ['latest_invoice.payment_intent'],
];
```

I'm thinking maybe that could be passed in as a parameter.

**Comment by edalzell** [comment]
Sounds like a reasonable FR.

**Comment by jeremydouglas** [comment]
Yes thanks for changing that. I've altered the add-on to work with Canadian taxes as I need. I may push that to a Github fork if. you're ok with that.

**Comment by edalzell** [comment]
PRs happily accepted

**Comment by edalzell** [comment]
Not going to add this in this version, if still required I'll add in v4 (Statamic v3), please re-open there if needed.
