### ISSUE TITLE
Plans with Trial periods don't return as "success" 

### ISSUE THREAD

**Issue by pmoignard** [edalzell/statamic-charge#73]
Plans with Trial periods in Stripe don't fire a "success" state when form is submitted. Works fine for plans without a trial.

**Comment by edalzell** [comment]
@pmoignard does the subscription get created properly with the trial?

**Comment by pmoignard** [comment]
Yep.

**Comment by pmoignard** [comment]
Since you fixed this, the {{ sucesss }} message is scoping weird. When I have more than one form on a page, submitting the form fires all of the success messages instead of just the one in the form that was submitted.

**Comment by edalzell** [comment]
That's a separate issue opened an issue for it: #75

**Comment by pmoignard** [comment]
Sounds good. Thx.
