### ISSUE TITLE
Make Amount optional in data-secret to allow amount to be set in JS instead.

### ISSUE THREAD

**Issue by sheldonkotyk** [edalzell/statamic-charge#76]
From our chat

ok, I've run into a blocker in using the new charge. I need to pass the amount into the charge parameter. I'm doing a two step form, The first page gets the amount and quantity, the second page needs to take the vars and do maths. ```{{ post }}{{ amount | multiply:quantity | multiply: 100 }}{{ /post }}```

I don't know how I can pass that integer into the ```data-secret="{{ charge:payment_intent name="Donation" amount="1000" }}"``` parameter to replace the amount in there. I've tried removing one of the parenthesis ``` amount="{ post}{ amount | multiply:quantity | multiply:100}{ /post }"``` but that doesn't work either. I've tried doing some direct php but antlers doesn't recognize the new variable. 

It looks like amount can be set in the js.
```var sourceData = {
    type: 'ideal',
    amount: 1099,
    currency: 'eur',
    owner: {
      name: document.querySelector('input[name="name"]').value,
    },
    // Specify the URL to which the customer should be redirected
    // after paying.
    redirect: {
      return_url: 'https://shop.example.com/crtA6B28E1',
    },
  };```

**Comment by edalzell** [comment]
I got the above to work, as per our Discord chat, it's possibly another interaction causing the issue.
