### ISSUE TITLE
Problem with webhook? and keys? on live site, but not on local

### ISSUE THREAD

**Issue by pmoignard** [edalzell/statamic-charge#79]
On **local**, everything works swimmingly. Customer created in Stripe, card added to customer, subscription created and role added to user, emails sent. Local is running PHP 7.3.5, and uses a test webhook and test keys to test the integration.

However, on **live**: Customer created in Stripe, card added to customer... but then the subscription fails, and no role is added to the user. No errors reported on the form itself, but live webhook returns the attached Internal Server Error (500) on all attempts in Stripe. Website server runs PHP 7.4. Error reads: "FatalThrowableError in SendEmailAction.php line 19:
Type error: Argument 1 passed to Statamic\Addons\Charge\Actions\SendEmailAction::execute() must be of the type string, null given, called in /home/forge/rsvpministries.com/site/addons/Charge/Traits/HandlesWebhook.php on line 69"

Things tried:
- Checked Charge CP to ensure the live plans are being pulled in from Stripe.
- Ensured that live keys and webhook secure secret are correct and the LIVE keys are in the live ENV.
- Ensured that live products and plans are the same config as the test ones.

The test integration continues to work just fine with the test keys and test hook, and the live one continues to make me lose my small amount of remaining hair by not working at all.

[error.txt](https://github.com/edalzell/statamic-charge/files/4578203/error.txt)

**Comment by edalzell** [comment]
Looks like that is this line:
```
            Arr::get($data, 'charges.data.0.receipt_email'),
```

Do you have an email set for that in Stripe?

**Comment by pmoignard** [comment]
Nope. But I didn't have it set for the test integration either?

**Comment by edalzell** [comment]
Looks like it is set on the front end? Here's where I have it in my testing:

![image](https://user-images.githubusercontent.com/6069653/81021998-5dfabd80-8e21-11ea-8482-6f69d437fe92.png)

**Comment by pmoignard** [comment]
Yeah, don't have that. Is that required for a live integration?

**Comment by edalzell** [comment]
Aren't you sending a receipt?

**Comment by pmoignard** [comment]
When someone subscribes to a subscription, they get a confirmation email, yeah. But I'm not sending the email as part of the stripe JS.

**Comment by pmoignard** [comment]
Didn't know it was necessary to send there because my test integration worked fine.

**Comment by pmoignard** [comment]
I fixed it. The problem was the IDs of the Stripe plans. When I copied them over to live, the IDs were changed automatically for the live plans, and those didn't match my integration.
