### ISSUE TITLE
Bug:  chargeId can't be added to form

### ISSUE THREAD

**Issue by axelferdinand** [edalzell/statamic-charge#80]
In the docs...
https://github.com/edalzell/statamic-charge/blob/master/docs/one-time/elements.md

...this line creates an undefined error:
```
// if you want to record the charge id in the order form
          // add it to the form
          var chargeId = result.paymentIntent.charges.data[0].id;
```

Would be nice to add the transaction ID to the form, but it doesn't work.

**Comment by edalzell** [comment]
what is undefined?

**Comment by edalzell** [comment]
Closing due to lack of response, please re-open if it's still an issue.
