### ISSUE TITLE
Feature Request: Support associating a charge with a Stripe Product SKU

### ISSUE THREAD

**Issue by timichango** [edalzell/statamic-charge#9]
Not sure how involved this is, but it'd be pretty useful if Charge supported connecting a charge to a Stripe product / creating a Stripe order. Still thinking of this in the context of a one-time charge, but being able to have a given charge leverage that Stripe functionality would open up a lot of flexibility for a simple cartless checkout flow for purchasing physical goods.

**Comment by edalzell** [comment]
How would you envision this working, can you give a flow?

**Comment by edalzell** [comment]
@timichango can you explain how you'd like to use it, from a template perspective?

**Comment by edalzell** [comment]
this is e-commerce, out of scope for Charge
